version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: thinkstack_redis
    restart: always
    ports:
      - '6375:6379'
    volumes:
      - redisdata:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: thinkstack_web
    restart: always
    ports:
      - '5173:5173'
    tty: true
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis

volumes:
  redisdata:
